version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: spotdl
    versions:
    - 3.3.1
    - 3.3.2
    - 3.3.3
    - 3.4.0
    - 3.4.2
    - 3.5.0
  - dependency-name: virtualenv
    versions:
    - 20.4.0
    - 20.4.1
    - 20.4.2
    - 20.4.3
  - dependency-name: soupsieve
    versions:
    - "2.1"
    - "2.2"
  - dependency-name: packaging
    versions:
    - "20.8"
