name: Docker Runner 

on:
  push:
    branches: [ master ]

jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#       - uses: actions/checkout@v3

#       - name: Login to Docker Hub
#         uses: docker/login-action@v3
#         with:
#           username: ${{ secrets.DOCKER_USERNAME }}
#           password: ${{ secrets.DOCKER_TOKEN }}

#       - name: Build and Push
#         uses: docker/build-push-action@v5
#         with:
#           context: .
#           push: true
#           tags: beanbubger/johnson-bot:latest

  deploy:
    runs-on: self-hosted
    environment: production 

    steps:
      - name: Pull Image 
        run: docker pull beanbubger/johnson-bot

      - name: Stop Johnson
        run: docker stop johnson

      - name: Remove Johnson
        run: docker container rm johnson

      - name: Run Container
        run: docker run --name johnson beanbubger/johnson-bot
        env:
              TOKEN: ${{ secrets.TOKEN }}
              SPOTIPY_CLIENT_SECRET: ${{ secrets.SPOTIPY_CLIENT_SECRET }}
              SPOTIPY_CLIENT_ID: ${{ secrets.SPOTIPY_CLIENT_ID }}
              SPOTIPY_REDIRECT_URI: ${{ secrets.SPOTIPY_REDIRECT_URI }}
              LEVEL: ${{ secrets.LEVEL }}
              DISCORD_HOST: ${{ secrets.DISCORD_HOST }}

      - name: Cleanup Unused Images
        run: docker image prune -f